name: Build

on:
  push:
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  plugin:
    name: HelloZig / ${{ matrix.toolchain }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { toolchain: zig, os: ubuntu-latest, release: true }
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@v7
      - uses: nsis-dev/build-plugin@main
        with:
          name: HelloZig
          toolchain: ${{ matrix.toolchain }}
          release: ${{ matrix.release }}
          sources: Contrib/HelloZig/*.c
          targets: x86-ansi,x86-unicode,amd64-unicode,arm64-unicode
